(function(g){var window=this;var J6=function(a,b){return g.aa[a]=b},Jua=function(a,b){var c=new g.oI;
c.o=a.o;c.D=a.D;c.C=a.C;c.B=a.B;c.G=a.G;c.F=a.F;c.J=a.J;c.g=b;return c},K6=function(a){return a.g?a.g.languageCode:a.o},L6=function(a){var b={format:a.A,
languageCode:a.o,languageName:a.D,displayName:g.pI(a),kind:a.B,name:a.C,id:a.Ba,is_servable:a.O,is_translateable:a.G,vss_id:a.F};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},M6=function(a){if(!Kua.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Lua,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},Mua=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},Nua=function(a){for(var b in a)delete a[b]},N6=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.oJ.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.C=f;this.o=k},O6=function(a,b,c,d,e){g.oJ.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},Q6=function(a){a=void 0===a?{}:a;
var b="_"+P6++;return new O6(0,0x8000000000000,0,b,a)},T6=function(a,b,c,d,e,f){var k={};
g.Ba(k,b);g.Ba(k,a.params);g.Ba(k,c);var l={};g.Ba(l,b.tb);a.params.tb&&g.Ba(l,a.params.tb);g.Ba(l,c.tb);k.tb=l;g.W.call(this,{H:"div",N:"caption-window",T:{id:"caption-window-"+a.id,dir:k.Kj==R6.pp?"rtl":"ltr",tabindex:0,"aria-live":"assertive",lang:k.lang},L:[{H:"span",N:"captions-text"}]});this.B=[];this.K=!1;this.F=a;this.D=[];this.G=[];this.va=e;this.ua=f;this.C=null;this.X=.96*e;this.ha=.96*f;this.o=k;this.sa=c;this.A=this.wa["captions-text"];this.ka=null!=this.A.style["box-decoration-break"]||
null!=this.A.style["-webkit-box-decoration-break"];this.M=d/360*16;this.type=S6.lp;this.da=this.M*Oua(l);a=new g.TF(this.element,!0);g.L(this,a);a.subscribe("dragstart",this.ML,this);a.subscribe("dragmove",this.LL,this);a.subscribe("dragend",this.KL,this);this.ga=this.fa=0;a="";this.o.Rj&&(a=M6(this.o.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.o.Rj+")");b={"background-color":a,display:!1===this.o.isVisible?"none":"","text-align":Pua[this.o.textAlign]};this.ka&&(b["border-radius"]=a?this.da/
8+"px":"");g.ah(this.element,b);switch(this.o.Og){case 0:case 1:case 2:g.R(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.R(this.element,"ytp-caption-window-bottom")}},Oua=function(a){var b=1+.25*(a.Si||0);
if(a.offset==U6.Zu||a.offset==U6.cv)b*=.8;return b},V6=function(a,b){var c={},d=b.background?b.background:a.o.tb.background;
if(null!=b.Ue||b.background){var e=null!=b.Ue?b.Ue:a.o.tb.Ue;d=M6(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.ka&&(c["box-decoration-break"]="clone",c["border-radius"]=a.da/8+"px")}if(null!=b.Si||null!=b.offset)c["font-size"]=a.M*Oua(b)+"px";d=1;e=b.color||a.o.tb.color;if(b.color||null!=b.zh)e=M6(e),d=null==b.zh?a.o.tb.zh:b.zh,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;var f=b.Oh;f==g.u3.NONE&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+
d+")";b.Rv&&(k=e=b.Rv);var l=a.M/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1),d=[];switch(f){case g.u3.DROP_SHADOW:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case g.u3.RAISED:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case g.u3.DEPRESSED:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case g.u3.hv:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case g.w3.Hu:e=
'"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case g.w3.Mu:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case g.w3.Gu:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case g.w3.CASUAL:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case g.w3.CURSIVE:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case g.w3.qp:e=g.QE()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case g.w3.vu:case g.w3.mp:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.o.tb.offset);switch(e){case U6.Zu:c["vertical-align"]="sub";break;case U6.cv:c["vertical-align"]="super"}b.fontFamily==g.w3.qp&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Cr&&(c["font-style"]="italic");b.Ct&&(c["text-decoration"]=
"underline");b.Rq&&(c.visibility="hidden");return c},Qua=function(a,b,c){a.K=a.K||!!c;
var d={};g.Ba(d,a.o.tb);g.Ba(d,c||b.o);g.Ba(d,a.sa.tb);c=a.D[0];if(c&&d.background==c.background&&d.Ue==c.Ue&&!!d.Rq==!!c.Rq&&d.Oh==c.Oh){var e;for(e=0;e<a.D.length;e++)if(Mua(d,a.D[e])){var f=a.G[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.je("SPAN");g.ah(f,V6(a,e));a.G[0].appendChild(f);e=1}a.G.length=e;a.D.length=e}else a.G.length=0,a.D.length=0,f=g.je("SPAN"),g.ah(f,V6(a,d)),a.A.appendChild(f);a.C&&a.C.parentNode!=f&&(g.qe(a.C),f.appendChild(a.C));c=(k=g.u(b.text))?b.text.split("\n"):
[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.B.length||!b.C){if(0<e||0!=a.B.length){var m=g.je("BR");f.appendChild(m)}f.appendChild(g.ke("\u00a0"));a.C=g.ke("\u00a0");f.appendChild(a.C)}l&&(m=a.C,m.parentNode&&m.parentNode.insertBefore(k?g.ke(l):l,m))}a.D.push(d);a.G.push(f);a.B.push(b)},Rua=function(){},X6=function(a){this.F=a;
this.B=this.o=this.mode=this.A=0;this.C=new W6(this);this.D=new W6(this);this.g=[];this.clear()},Tua=function(a,b,c){if(255==a&&255==b||!a&&!b)return{jm:a,
km:b,result:0};a=Sua[a];b=Sua[b];if(a&128){if(!(b&128)&&0!=c.g&&c.o==b)return{jm:a,km:b,result:1}}else if(b&128&&1<=a&&31>=a)return{jm:a,km:b,result:2};return{jm:a,km:b,result:3}},Vua=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.B&&a.reset(),a.C.g.clear(),a.D.g.clear()):(a.B=0,Uua(a.C,b,c,d))},Wua=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.o=d.time;0==d.type?Vua(a,d.Mv,d.Nv,b):1==d.type&&a.A&496&&Uua(a.D,d.Mv,d.Nv,b)}a.g.length=0},Y6=function(){this.g=0},Z6=function(){this.o=this.A=this.g=0},$6=function(){this.timestamp=this.uf=0;
this.g=!1},a7=function(a){this.A=[];
for(var b=0;15>=b;b++){this.A[b]=[];for(var c=0;32>=c;c++)this.A[b][c]=new $6}this.g=this.o=this.Oc=0;this.style=new Y6;this.C=a;this.B=0},b7=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.C.o+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.A[m][q];
if(0!=r.uf){0==c&&(c=m,d=q);var n=String.fromCharCode(r.uf),w=r.timestamp;w<e&&(e=w);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.uf||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.C.o+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.A[k][m],r=q.uf,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),w=q.timestamp,w<=e&&(e=w),l+=n,q.reset()),32==m||0==r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},ava=function(a,b){switch(a){case 0:return Xua[(b&127)-32];
case 1:return Yua[b&15];case 2:return Zua[b&31];case 3:return $ua[b&31]}return 0},c7=function(a){return a.A[a.Oc][a.o]},d7=function(a,b,c){2<=b&&1<a.o&&(--a.o,c7(a).uf=0);
var d=c7(a);d.timestamp=a.C.o+0;d.uf=ava(b,c);32>a.o&&a.o++},bva=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.A[b+e][f].Fm(a.A[c+e][f])},e7=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},f7=function(a){a.Oc=0<a.g?a.g:1;
a.o=1;e7(a,0,15)},g7=function(a){this.B=a;
this.C=0;this.style=new Y6;this.D=new a7(a);this.F=new a7(a);this.G=new a7(a);this.o=this.D;this.A=this.F;this.g=this.o},h7=function(a,b,c){var d=a.o,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:b7(d,c),f7(a.o),f7(a.A),d.Oc=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.B.mode=1<<d.B;e?d.o=1:d.g!=b&&(d.g>b?(b7(d,c),e7(d,d.Oc-d.g,b)):d.Oc<b&&(b=d.g),d.g=b)},cva=function(a){a.style.set(1);
a.g=a.A;a.g.g=0;a.g.style=a.style;a.B.mode=1<<a.g.B},dva=function(a){a.style.set(4);
a.g=a.G;a.g.style=a.style;a.B.mode=1<<a.g.B},W6=function(a){this.o=a;
this.g=new Z6;this.C=0;this.A=new g7(a);this.D=new g7(a);this.B=this.A},Uua=function(a,b,c,d){a.g.update();
b=Tua(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.jm;c=b.km;if(32<=e||!e)a.o.mode&a.o.A&&(b=e,b&128&&(b=127),c&128&&(c=127),e=a.B.g,b&96&&d7(e,0,b),c&96&&d7(e,0,c),!a.o.F&&0!=b&&0!=c&&3==e.style.g&&b7(e,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.A=e,b.o=c,b.g=2,b=e&8?a.D:a.A,a.B=b,a.o.mode=1<<(a.C<<2)+(b.C<<1)+(4==b.style.g?1:0),(a.o.mode|1<<(a.C<<2)+(b.C<<1)+(4!=b.style.g?1:0))&a.o.A))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&
14)>>1):0;c=b.g;switch(b.style.get()){case 4:d=c.Oc;break;case 3:if(d!=c.Oc){if(d<c.g&&(d=c.g,d==c.Oc))break;var f=1+c.Oc-c.g,k=1+d-c.g;bva(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));e7(c,b,e)}}c.Oc=d;c.o=a+1}else switch(e&7){case 1:switch(c&112){case 32:d7(b.g,0,32);break a;case 48:57==c?(b=b.g,c7(b).uf=0,32>b.o&&b.o++):d7(b.g,1,c&15)}break;case 2:c&32&&d7(b.g,2,c&31);break;case 3:c&32&&d7(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:cva(b);break;
case 33:b=b.g;1<b.o&&(--b.o,c7(b).uf=0);break;case 36:b=b.g;d=c7(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.A[a][c]==d){for(;32>=c;c++)b.A[a][c].reset();break}break;case 37:h7(b,2,d);break;case 38:h7(b,3,d);break;case 39:h7(b,4,d);break;case 40:d7(b.g,0,32);break;case 41:b.style.set(2);b.g=b.o;b.g.g=0;b.g.style=b.style;b.B.mode=1<<b.g.B;break;case 42:d=b.G;d.g=15;d.style.set(4);f7(d);dva(b);break;case 43:dva(b);break;case 44:a=b.o;switch(b.style.get()){case 1:case 2:case 3:b7(a,d)}e7(a,0,15);break;
case 45:b:{a=b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.Oc){++a.Oc;a.o=1;break b}case 3:}2>a.g&&(a.g=2,a.Oc<a.g&&(a.Oc=a.g));b=a.Oc-a.g+1;b7(a,d);bva(a,b,b+1,a.g-1);e7(a,a.Oc,1)}break;case 46:e7(b.A,0,15);break;case 47:b7(b.o,d);d=b.A;a=b.B.o+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.A[c][e].timestamp=a;d=b.A;b.A=b.o;b.o=d;cva(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.o+=c&3)&&(b.o=32)}}},i7=function(){},j7=function(a){this.A=a;
this.o=null},fva=function(a,b,c){var d=a.getAttribute("t"),d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0),e=a.getAttribute("d"),e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);
b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?k7.rp:k7.Rl;a=g.lr("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");eva(d,e,k,b,f,a.firstChild,{},c)},eva=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.Cr=!0;break;case "u":k.Ct=!0;break;case "font":var m=f.getAttribute("color");l7.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new N6(a,b,c,d,n.nodeValue,e||0<m,g.Ub(k)?void 0:k));else{var q={};g.Ba(q,k);eva(a,b,c,d,e||0<m,n,q,l)}}},m7=function(){this.A={};
this.o=null},n7=function(a){this.o={};
this.C={};this.D={};this.A="_"+P6++;this.B=a},o7=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},p7=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},q7=function(a,b){var c=o7(a,b);
if(void 0!=c)return c},r7=function(a,b){var c=a.getAttribute(b);
if(null!=c)return l7.test(c),c},gva=function(a,b){var c={},d=b.getAttribute("ws");
g.Ba(c,d?a.D[d]:a.B);d=q7(b,"mh");null!=d&&(c.Or=d);d=q7(b,"ju");null!=d&&(c.textAlign=d);d=q7(b,"pd");null!=d&&(c.Kj=d);d=r7(b,"wfc");null!=d&&(c.windowColor=d);d=o7(b,"wfo");void 0!=d&&(c.Rj=d/255);return c},hva=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ba(c,a.C[d]);d=q7(b,"ap");null!=d&&(c.Og=d);d=o7(b,"cc");null!=d&&(c.HG=d);d=o7(b,"ah");null!=d&&(c.ki=d);d=o7(b,"rc");null!=d&&(c.mo=d);d=o7(b,"av");null!=d&&(c.Di=d);return c},iva=function(a,b,c){var d={};
g.Ba(d,hva(a,b));g.Ba(d,gva(a,b));c?Mua(d,a.B)?(c=a.A,d=a.B):c="_"+P6++:c=b.getAttribute("id")||"0";a=o7(b,"t");b=o7(b,"d")||0x8000000000000;return new O6(a,b,0,c,d)},s7=function(a,b,c){this.F=c;
this.version=this.C=this.D=this.g=0;this.o=new window.DataView(a);this.A=[]},t7=function(a){var b=a.g;
a.g+=1;return a.o.getUint8(b)},jva=function(a){var b=a.g;
a.g+=4;return a.o.getUint32(b)},u7=function(a,b){this.B=a;
this.o="CC3"==b.D?4:0;this.A=new X6(!1);this.A.A=1<<this.o},kva=function(a){if(!(a.g<a.o.byteLength))return!1;
var b=jva(a);b.toString(16);if(1380139777!=b)return!1;a.version=t7(a);if(1<a.version)return!1;t7(a);t7(a);t7(a);return!0},lva=function(){this.o=[];
this.g=[]},v7=function(a,b){return b?a.g.concat(a.o):a.g},w7=function(a,b){switch(b.B){case "asr":var c=a.o;
g.ab(c,(0,g.y)(b.K,b))||c.push(b);break;default:c=a.g,g.ab(c,(0,g.y)(b.K,b))||c.push(b)}},x7=function(){this.o=null},mva=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Cr=!0;break;case "u":l.Ct=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new N6(b,c,d,e.id,q.nodeValue,f||0<n,g.Ub(l)?void 0:l),m.push(q),e!=a.o&&e.o.push(q);else{var r={};g.Ba(r,l);mva(a,b,c,d,e,!0,q,r,m)}}},y7=function(a){var b=0;
a=g.ka(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+c.value;return 1E3*b},z7=function(a){this.Vx=!!a;
this.o=new lva;this.C=[];this.g=null},ova=function(a){var b={};
if(a=K6(a))b.lang=a,nva.test(a)&&(b.Kj=R6.pp);return b},pva=function(a,b,c,d,e){d=d||0;
e=e||0;if(g.u(b)){if("WEBVTT"==b.substring(0,6))return a.g||(a.g=new x7),a.g.g(b,d);b=g.lr(b);if(!b||!b.firstChild)return[];a.g||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.g=new n7(ova(c)):a.g=new m7:a.g=new j7(ova(c)));return a.g.g(b,d)}try{if(g.u(b))var f=!1;else{var k=new s7(b,0,0);f=kva(k)}if(f)return a.g||(a.g=new u7(e,c)),a.g.g(b,d)}catch(l){g.rE(l)}return[]},A7=function(a){z7.call(this,a.sm);
this.B=void 0;this.A=null;this.C=a.captionTranslationLanguages},B7=function(){this.sb=[]},C7=function(a,b,c,d,e,f){g.K.call(this);
this.M=a;this.K=b;this.B=new B7;this.g=null;this.D=d;this.J=f;this.o=this.A=null;this.O=c;this.C=e||!1;this.F=new g.rt(this.my,1E3,this);g.L(this,this.F);this.G=new g.OF(this);g.L(this,this.G);this.G.R(b,"seekto",this.gz);this.gz(b.getCurrentTime());this.my()},D7=function(a,b){z7.call(this);
this.D=a;this.U=b;this.A=null;this.B=!1},E7=function(a,b,c,d,e,f){T6.call(this,a,b,c,d,e,f);
this.type=S6.kp},F7=function(a,b,c,d,e,f){T6.call(this,a,b,c,d,e,f);
g.R(this.element,"ytp-caption-window-rollup");this.type=S6.np;this.J=this.O=0;this.P=window.NaN;this.pa=null;this.ba=new g.rt(this.pQ,433,this);g.L(this,this.ba)},G7=function(a){if(!a.O){var b=g.je("SPAN");
g.ah(b,V6(a,a.o.tb));a.A.appendChild(b);b.appendChild(g.ke("M"));var c=b.offsetHeight,d=g.je("BR");b.appendChild(d);b.appendChild(g.ke("M"));a.O=b.offsetHeight-c;a.A.removeChild(b)}return a.O},H7=function(a,b,c,d){z7.call(this,d);
c=c||g.GE(a).hl||"";c=c.split("_").join("-");this.B=g.IE(a,{hl:c});this.D=b;this.F={};this.A=null},L7=function(a){g.sV.call(this,a);
g.SD();this.Z=g.Y(a);this.o=a.ia();this.ha=g.OU(a);this.U=a;var b=null,c=g.vD("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.jD(c));this.ca=b;this.C={tb:{}};this.F={tb:{}};this.J=[];this.K={};this.P={};this.O=!1;this.ka="1"==this.o.ac.cc_auto_caps||"1"==this.Z.O.cc_auto_caps;c=b=this.A=this.B=this.D=this.G=this.M=this.fa=null;I7(this)||(b=new g.ot(this.fC,void 0,this),g.L(this,b),c=new g.rt(this.cS,2E3,this),g.L(this,c));this.da=b;this.ga=c;this.X=new g.OF(this);g.L(this,this.X);I7(this)||
this.X.R(a,"resize",this.Et);this.X.R(a,"onPlaybackAudioChange",this.EN);this.X.R(a,"crn_captions",this.xL,this);this.X.R(a,"crx_captions",this.yL,this);J7(this,K7(this,"display-settings")||{});qva(this)&&this.load()},I7=function(a){if("3"!=a.Z.C)return!1;
a=a.U.app.D;return!(!a||!a.g.textTracks)},rva=function(a){if(a.o.captionTracks.length)var b=a.g.nh().Jv;
if("FORCED_ON"==b||1==a.Z.Sg||1==a.o.Sg||"alwayson"==g.xP(a.o,"yt:cc"))return!0;if(2==a.Z.Sg){var c=K7(a,"module-enabled");if(null!=c)return!!c}return"ON"==b||"on"==g.xP(a.o,"yt:cc")},qva=function(a){return I7(a)?!a.o.Da:a.o.captionTracks.length&&a.g.nh().tk?!0:rva(a)},sva=function(a,b){if(a.B){var c=v7(a.B.o,b||a.ka);
if(a.D&&a.D.g)return a.D.g;if(!a.Z.experiments.g("legacy_default_caption_track"))for(var d=[a.o.Rg,a.Z.Rg,g.xP(a.o,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(K6(c[f])==d[e])return c[f];return a.D&&a.D.eq?a.D.eq:c[0]||a.D&&a.D.tk}return null},M7=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.O=c);a.A=b;a.load(d)},tva=function(a,b){var c=g.WY(a.ha,!0).height;
if(!c)return null;var d=a.ha.Za();switch(null!=b.params.Or?b.params.Or:b.params.IS?S6.np:1<b.o.length?S6.kp:S6.lp){case S6.kp:return new E7(b,a.C,a.F,c,d.width,d.height);case S6.np:return new F7(b,a.C,a.F,c,d.width,d.height);default:return new T6(b,a.C,a.F,c,d.width,d.height)}},J7=function(a,b,c){var d=N7.tb;
a.C={};g.Ba(a.C,N7);a.C.tb={};g.Ba(a.C.tb,d);a.F={tb:{}};var e=b.backgroundOverride?a.F:a.C,f=b.background||d.background;l7.test(f);e.tb.background=f;e=b.colorOverride?a.F:a.C;f=b.color||d.color;l7.test(f);e.tb.color=f;e=b.windowColorOverride?a.F:a.C;f=b.windowColor||N7.windowColor;l7.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.F:a.C;f=b.backgroundOpacity;null==f&&(f=d.Ue);e.tb.Ue=f;e=b.fontSizeIncrementOverride?a.F:a.C;f=b.fontSizeIncrement;null==f&&(f=d.Si);e.tb.Si=f;e=b.textOpacityOverride?
a.F:a.C;f=b.textOpacity;null==f&&(f=d.zh);e.tb.zh=f;e=b.windowOpacityOverride?a.F:a.C;f=b.windowOpacity;null==f&&(f=N7.Rj);e.Rj=f;e=b.charEdgeStyleOverride?a.F:a.C;f=b.charEdgeStyle;null==f&&(f=d.Oh);e.tb.Oh=f;e=b.fontFamilyOverride?a.F:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.tb.fontFamily=f;a.loaded&&a.Et();c&&O7(a,"display-settings",b)},vva=function(a,b){if(b&&!a.G){var c=Q6({Kj:R6.jp,
lang:"en"});a.G=[c,new N6(c.start,c.end-c.start,0,c.id,g.T("YTP_SAMPLE_SUBTITLES"))];g.aV(a.g,a.G)}else!b&&a.G&&(uva(a,a.G),a.G=null)},uva=function(a,b){g.cV(a.g,b);
(0,g.G)(b,function(a){g.nb(this.J,a)},a);
a.da.Bk()},wva=function(a,b){return a&&g.u(a)&&l7.test(a)?a:b},xva=function(a,b){return g.oa(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},zva=function(a,b){if(a&&g.u(a)){var c=yva.indexOf(a);
return-1!=c?c:b}return b},Bva=function(a,b){if(a&&g.u(a)){var c=Ava.indexOf(a);
return-1!=c?c:b}return b},Cva=function(a,b){return g.oa(a)&&!(0,window.isNaN)(a)?g.Id(a,-2,4):b},K7=function(a,b){if(!a.ca)return null;
try{var c=a.ca.get(b)}catch(d){a.ca.remove(b)}return c},O7=function(a,b,c){if(a.ca)try{a.ca.set(b,c)}catch(d){}};
g.rJ.prototype.an=J6(2,function(a){return(a=this.Th(a))?a.o:0});
g.PL.prototype.an=J6(1,function(){return 0});
g.oI.prototype.K=J6(0,function(a){return a?this.toString()==a.toString():!1});
var Kua=/^#(?:[0-9a-f]{3}){1,2}$/i,Lua=/#(.)(.)(.)/,nva=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,U6={Zu:0,NORMAL:1,cv:2},Ava="default monoSerif propSerif monoSans propSans casual cursive smallCaps".split(" "),yva=["none","raised","depressed","uniform","dropShadow"],l7=/^#(?:[0-9a-f]{3}){1,2}$/i;var P7={Du:0,E_:1,ND:2},Pua=["left","right","center"],R6={jp:0,pp:1,y0:2,BV:3},k7={U1:0,Rl:5,rp:6},S6={lp:0,kp:1,np:2};var N7={windowColor:g.v3.Yo,Rj:0,textAlign:P7.ND,Og:7,ki:50,Di:100,tb:{background:g.v3.Yo,Ue:.75,Oh:g.u3.NONE,color:g.v3.tp,fontFamily:g.w3.mp,Si:0,zh:1,offset:U6.NORMAL}};g.p(N6,g.oJ);N6.prototype.toString=function(){return g.oJ.prototype.toString.call(this)};g.p(O6,g.oJ);O6.prototype.toString=function(){return g.oJ.prototype.toString.call(this)};
var P6=0;g.p(T6,g.W);g.h=T6.prototype;g.h.ML=function(a,b){var c=g.qh(this.element,this.element.parentElement);this.fa=a-c.x;this.ga=b-c.y;g.R(this.element,"ytp-dragging")};
g.h.LL=function(a,b){var c=g.th(this.element),d=a-this.fa-.02*this.va,e=b-this.ga-.02*this.ua,f=(d+c.width/2)/this.X*3,f=Math.floor(g.Id(f,0,2)),k=(e+c.height/2)/this.ha*3,k=Math.floor(g.Id(k,0,2)),l=f+3*k,d=(d+f/2*c.width)/this.X,d=100*g.Id(d,0,1),c=(e+k/2*c.height)/this.ha,c=100*g.Id(c,0,1);this.F.params.Og=l;this.F.params.Di=c;this.F.params.ki=d;this.o.Og=l;this.o.Di=c;this.o.ki=d;this.oB()};
g.h.KL=function(){g.Ip(this.element,"ytp-dragging")};
g.h.oB=function(){this.Ai(this.B)};
g.h.bc=function(){return this.type};
g.h.Ai=function(a){var b=Math.min(this.Sw(),this.X),c=this.Rw();g.ah(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"96%",height:c?c+"px":"96%",margin:"",transform:""});this.Ip(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":""};var d=.96*this.o.ki+2,e=this.o.Og;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.A.offsetWidth;b||d?a["margin-left"]=(b||d+1)/-2+"px":a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=
100-d+"%"}b=.96*this.o.Di+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.A.offsetHeight)?a["margin-top"]=c/-2+"px":a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.ah(this.element,a)};
g.h.Ip=function(a){var b;for(b=0;b<a.length&&a[b]==this.B[b];b++);if(this.K||this.B.length>b)b=0,this.K=!1,this.B=[],this.D=[],this.G=[],this.C=null,g.ne(this.A);for(;b<a.length;b++)Qua(this,a[b])};
g.h.Sw=function(){return 0};
g.h.Rw=function(){return 0};
g.h.toString=function(){return g.W.prototype.toString.call(this)};Rua.prototype.B=function(){};X6.prototype.clear=function(){this.B=this.o=this.mode=0;this.g=[];this.reset()};
X6.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var Sua=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];Y6.prototype.set=function(a){this.g=a};
Y6.prototype.get=function(){return this.g};
Z6.prototype.clear=function(){this.g=0};
Z6.prototype.update=function(){this.g=2==this.g?1:0};
Z6.prototype.matches=function(a,b){return 0!=this.g&&a==this.A&&b==this.o};
$6.prototype.Fm=function(a){this.uf=a.uf;this.timestamp=a.timestamp;this.g=a.g};
$6.prototype.reset=function(){this.timestamp=this.uf=0;this.g=!1};
a7.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.B=a;this.g=0;this.o=this.Oc=1};
var Xua=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Yua=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Zua=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],$ua=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];g7.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.o=this.D;this.A=this.F;this.g=this.o;var c=(a<<2)+(b<<1)+0;this.D.reset(c);this.F.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
W6.prototype.reset=function(a){this.C=a;this.g.clear();this.B=this.A;this.A.reset(a,0);this.D.reset(a,1)};i7.prototype.reset=function(){};g.p(j7,i7);j7.prototype.g=function(a){var b=[];this.o||(this.o=Q6(this.A),b.push(this.o));a=g.ka(a.firstChild.childNodes);for(var c=a.next();!c.done;c=a.next())fva(c.value,this.o.id,b);return b};g.p(m7,i7);
m7.prototype.g=function(a){var b=[];this.o||(this.o=Q6(),this.A[this.o.id]=this.o,b.push(this.o));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.A[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=Q6());
var k={};f&&(g.Ba(k,f.params),f=f.params.tb)&&(k.tb={},g.Ba(k.tb,f));e.getAttribute("rc")&&(k.mo=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.HG=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.Og=0>f||8<f?7:f);e.getAttribute("ah")&&(k.ki=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.Di=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.Kj=R6.pp,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.Kj=R6.jp));e.getAttribute("bc")&&(k.tb||(k.tb={}),k.tb.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.tb||(k.tb={}),k.tb.Ue=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.tb||(k.tb={}),k.tb.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.IS=(0,window.parseInt)(e.getAttribute("sd"),10));
f=(0,window.parseInt)(e.getAttribute("d"),10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"0";c=new O6(c,f,0,e,k)}else c=null}this.A[d]=c;b.push(c);break;case "text":for(d=[],fva(a,this.o.id,d),d=g.ka(d),c=d.next();!c.done;c=d.next())c=c.value,this.A[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.p(n7,i7);
n7.prototype.g=function(a){a.firstChild.getAttribute("format");a=g.ka(a.firstChild.childNodes);for(var b=a.next();!b.done;b=a.next())switch(b=b.value,b.tagName){case "head":var c=b;break;case "body":var d=b}if(c)for(c=g.ka(c.childNodes),a=c.next();!a.done;a=c.next())switch(a=a.value,a.tagName){case "pen":var b=a.getAttribute("id"),e=this.o,f={},k=a.getAttribute("p");k&&g.Ba(f,this.o[k]);k=p7(a,"b");null!=k&&(f.bold=k);k=p7(a,"i");null!=k&&(f.Cr=k);k=p7(a,"u");null!=k&&(f.Ct=k);k=q7(a,"et");null!=
k&&(f.Oh=k);k=q7(a,"of");null!=k&&(f.offset=k);k=r7(a,"bc");null!=k&&(f.background=k);k=r7(a,"ec");null!=k&&(f.Rv=k);k=r7(a,"fc");null!=k&&(f.color=k);k=q7(a,"fs");void 0!=k&&k!=g.w3.vu&&(f.fontFamily=k);k=o7(a,"sz");void 0!=k&&(f.Si=k/100-1);k=o7(a,"bo");void 0!=k&&(f.Ue=k/255);a=o7(a,"fo");void 0!=a&&(f.zh=a/255);e[b]=f;break;case "ws":b=a.getAttribute("id");this.D[b]=gva(this,a);break;case "wp":b=a.getAttribute("id"),this.C[b]=hva(this,a)}c=[];if(d){a={};var b=void 0;d=g.ka(d.childNodes);for(e=
d.next();!e.done;e=d.next())switch(e=e.value,e.tagName){case "w":var l=iva(this,e,!1);(e=a[l.id])&&e.end>l.start&&(e.end=l.start);a[l.id]=l;c.push(l);break;case "p":var m=b,n=Zf,f=[],k=e.getAttribute("w")||this.A,q=!!p7(e,"a"),r=o7(e,"t")||0,w=o7(e,"d")||5E3;!n&&!q&&m&&m.windowId==k&&m.end>r&&(m.end=r);for(var m=q?k7.rp:k7.Rl,n=this.o[e.getAttribute("p")],A=e.childNodes,C=0;C<A.length;C++){var B=A[C];0<C&&(q=!0);if("s"==B.tagName)var M=B,B=r,X=w,xa=k,db=q,fa=m,uc=M.textContent?M.textContent:"",eb=
this.o[M.getAttribute("p")],M=o7(M,"t")||0,B=new N6(B+M,X-M,fa,xa,uc,db,eb);else B=new N6(r,w,m,k,B.textContent||"",q,n);f.push(B)}b&&"\n"==b.text&&(b.text="");if(0<f.length){b=f[f.length-1];var Zf=null!=e.getAttribute("d");f[0].windowId==this.A&&(l=iva(this,e,!0),c.push(l));e=g.ka(f);for(f=e.next();!f.done;f=e.next())f=f.value,f.windowId=l.id,l.o.push(f),c.push(f)}}}return c};g.p(s7,Rua);s7.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+P6++;c=c/1E3-this.F;d=d/1E3-this.F;var k=k7.Rl;a=new O6(c,d-c,k,f,{textAlign:P7.Du,Og:0,ki:2.5*b,Di:5.33*a});e=new N6(c,d-c,k,f,e);this.A.push(a);this.A.push(e)}};
g.p(u7,i7);u7.prototype.g=function(a){a=new s7(a,0,this.B);if(kva(a)){for(;a.g<a.o.byteLength;)for(0==a.version&&(a.D=jva(a)*(1E3/45)),a.C=t7(a);0<a.C;a.C--){var b=t7(a),c=t7(a),d=t7(a);b&4&&(b&3)==this.o&&(0==this.o||1==this.o)&&(b=this.A,b.g.push({time:a.D,type:this.o,Mv:c,Nv:d,order:b.g.length}))}Wua(this.A,a);return a.A}return[]};
u7.prototype.reset=function(){this.A.clear()};g.p(x7,i7);
x7.prototype.g=function(a,b){for(var c=[],d=a.split(Dva),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Eva.test(f)){var l=Q7.exec(f);if(l&&3<=l.length){var m=y7(l[1]),l=y7(l[2])-m,m=m+k,f=f.substring(Q7.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");Q7.lastIndex=0;var n=f,f={};this.o||(this.o=Q6({Or:S6.lp}),c.push(this.o));var q=this.o,k=k7.Rl;if(0>n.indexOf("<"))c.push(new N6(m,l,k,q.id,n,!1,g.Ub(f)?void 0:f));else{n=n.split(Fva);1!=n.length&&(k=k7.rp,q="_"+Gva++,q=new O6(m,l,k,q,{}),c.push(q));
for(var r=m,w=0;w<n.length;w++){var A=n[w];if(0==w%2){var C=g.lr("<html>"+A+"</html>");if(C.getElementsByTagName("parsererror").length){var B=C.createElement("span");B.appendChild(C.createTextNode(A))}else B=C.firstChild;mva(this,r,l-(r-m),k,q,0<w,B,f,c)}else r=y7(A)}}}Q7.lastIndex=0}}return c};
var Gva=0,Eva=/^NOTE/,Dva=/(?:\r\n|\r|\n){2,}/,Q7=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3}).*(?:\r\n|\r|\n)","gm"),Fva=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.z(z7,g.K);z7.prototype.Hd=function(){this.g=null};
z7.prototype.W=function(){z7.aa.W.call(this);this.Hd()};
z7.prototype.ZA=function(){return!1};g.p(A7,z7);g.h=A7.prototype;g.h.Ir=function(a,b){var c=this.zk(a),d=(0,g.y)(function(c){this.A=null;b(c.responseText,a)},this);
this.Hd();this.A=g.LE(c,{format:"RAW",Ob:d,withCredentials:!0})};
g.h.Jr=function(a,b,c,d){this.B=c;if(d)for(b=g.ka(d.captionTracks),c=b.next();!c.done;c=b.next())w7(this.o,c.value);a()};
g.h.zk=function(a){var b=a.J,c={};if(this.B||a.A)c.fmt=this.B||"srv"+a.A;a.g&&(c.tlang=a.g.languageCode);return g.IE(b,c)};
g.h.Hd=function(){z7.prototype.Hd.call(this);this.A&&this.A.abort()};
g.h.W=function(){this.Hd();z7.prototype.W.call(this)};B7.prototype.contains=function(a){a=g.xb(this.sb,a);return 0<=a||0>a&&1==(-a-1)%2};
B7.prototype.length=function(){return this.sb.length/2};g.p(C7,g.K);g.h=C7.prototype;g.h.W=function(){g.K.prototype.W.call(this);this.o&&this.o.abort()};
g.h.gz=function(a){var b=this.g;this.g=g.Za(this.O.Yg(a).g);b!=this.g&&this.J&&this.J()};
g.h.reset=function(){this.B=new B7;this.o&&(this.o.abort(),this.o=null)};
g.h.my=function(){var a;if(a=null!==this.g)a=this.g,a=a.oa.pi(a);if(a&&!this.o&&!(this.g&&30<this.g.startTime-this.K.getCurrentTime())){a=this.g;a=a.oa.Xk(a);if(!this.B.contains(a.g[0].Ea)){var b=g.wL(g.AL(a,this.M,{})),c={format:"RAW",Fd:(0,g.y)(this.lQ,this),withCredentials:!0};this.C&&(c.responseType="arraybuffer");this.o=g.LE(b,c);this.A=a;var b=this.B,c=this.A.g[0].Ea,d=g.xb(b.sb,c);0<=d||0>d&&1==(-d-1)%2||(d=-d-1,0<d&&1==c-b.sb[d-1]&&d<b.sb.length&&1==b.sb[d]-c?(g.lb(b.sb,d),g.lb(b.sb,d-1)):
0<d&&1==c-b.sb[d-1]?b.sb[d-1]=c:d<b.sb.length&&1==b.sb[d]-c?b.sb[d]=c:(g.tb(b.sb,d,0,c),g.tb(b.sb,d+1,0,c)))}this.g=g.Za(a.g)}this.F.start()};
g.h.lQ=function(a){(this.C?!a.response:!a.responseText)||400<=a.status||null===this.D||(this.C?this.D(a.response,1E3*this.A.g[0].startTime):this.D(a.responseText,1E3*this.A.g[0].startTime));this.o=this.A=null};g.p(D7,z7);g.h=D7.prototype;g.h.Ir=function(a,b){this.Hd();var c=this.D.g[a.o];if(c){var d=1E3*c.index.an(c.index.rg()),e=g.Y(this.U).xf;this.A=new C7(new g.zK,this.U,c,function(c,e){b(c,a,e,d)},e,(0,g.y)(function(){e&&(this.A&&this.A.reset(),this.g&&this.g.reset(),this.B=!0)},this))}};
g.h.ZA=function(){var a=this.B;this.B=!1;return a};
g.h.Jr=function(a){g.Y(this.U).xf?(w7(this.o,new g.oI({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),w7(this.o,new g.oI({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}))):w7(this.o,new g.oI({format:1,languageCode:"en",languageName:"English",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));a()};
g.h.Hd=function(){z7.prototype.Hd.call(this);this.A&&(this.A.dispose(),this.A=null)};
g.h.zk=function(){return""};
g.h.W=function(){this.Hd();z7.prototype.W.call(this)};g.p(E7,T6);E7.prototype.Ip=function(a){var b=this.F.o;T6.prototype.Ip.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o==e)var d=f;else{d={};g.Ba(d,c.o);g.Ba(d,Hva);var e=c.o;var f=d}Qua(this,c,d)}};
var Hva={Rq:!0};g.p(F7,T6);g.h=F7.prototype;g.h.oB=function(){g.tt(this.ba)};
g.h.pQ=function(){g.Ip(this.element,"ytp-rollup-mode");this.Ai(this.pa,!0)};
g.h.Sw=function(){return this.J};
g.h.Rw=function(){return this.F.params.mo*G7(this)};
g.h.Ai=function(a,b){this.pa=a;if(G7(this)){for(var c=0,d=0;d<this.B.length&&c<a.length;d++)this.B[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.B.concat(a.slice(c)));c=this.J;this.J=0;T6.prototype.Ai.call(this,a);this.J=Math.max(c,this.A.offsetWidth+1);c=this.F.params.mo*G7(this)-this.A.offsetHeight;c!=this.P&&(b||(0,window.isNaN)(this.P)||(g.R(this.element,"ytp-rollup-mode"),this.ba.ce()),g.ah(this.A,"transform",c?"translateY("+c+"px)":""),this.P=c);T6.prototype.Ai.call(this,a)}else T6.prototype.Ai.call(this,
a)};g.z(H7,z7);g.h=H7.prototype;g.h.Ir=function(a,b){var c=this.zk(a),d=(0,g.y)(function(c){this.A=null;b(c.responseText,a)},this);
this.Hd();this.A=g.LE(c,{format:"RAW",Ob:d,withCredentials:!0})};
g.h.Jr=function(a,b,c){var d=this.B;b={type:"list",tlangs:1,v:this.D,fmts:Number(b||!1),vssids:1};this.Vx&&(b.asrs=1);d=g.IE(d,b);b=(0,g.y)(function(b){this.A=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.o,e=g.ka(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value,l=m.getAttribute("formats"),n=m.getAttribute("lang_code"),q=m.getAttribute("lang_translated"),r=m.getAttribute("name"),w=m.getAttribute("kind"),A=m.getAttribute("id"),C="true"==m.getAttribute("cantran"),
m=m.getAttribute("vss_id");w7(d,new g.oI({formats:l,format:c,languageCode:n,languageName:q,name:r,kind:w,id:A,is_servable:!0,is_translateable:C,vss_id:m}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),q=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),l={languageCode:l,languageName:n,languageOriginal:q,id:r},this.F[l.languageCode]=l.languageName,this.C.push(new g.nI(l))}a()},this);
this.Hd();this.A=g.LE(d,{format:"RAW",Ob:b,withCredentials:!0})};
g.h.zk=function(a){var b=this.B,c={v:this.D,type:"track",lang:a.o,name:a.C,kind:a.B,fmt:a.A};a.g&&(c.tlang=K6(a));return b=g.IE(b,c)};
g.h.Hd=function(){H7.aa.Hd.call(this);this.A&&this.A.abort()};
g.h.W=function(){this.Hd();H7.aa.W.call(this)};g.p(L7,g.sV);g.h=L7.prototype;g.h.W=function(){I7(this)||vva(this,!1);g.sV.prototype.W.call(this)};
g.h.load=function(a){g.sV.prototype.load.call(this);this.D=this.g.nh();if(this.B||a)this.A?(a?this.IA(a,this.A):3!=this.g.Xa()&&this.B.Ir(this.A,(0,g.y)(this.IA,this)),this.g.za("captionschanged",L6(this.A))):this.g.za("onCaptionsTrackListChanged");else{var b;a=this.o;a.Da||g.Y(this.U).xf&&null!=a.xa&&null!=a.xa.g.rawcc?b=new D7(this.o.xa,this.g):this.o.captionTracks.length?b=new A7(this.o):b=new H7(this.o.tm,this.o.videoId,this.o.Rg||this.Z.Rg||g.xP(this.o,"yt:cc_default_lang")||this.Z.Ja,this.o.sm);
this.B=b;b.Jr((0,g.y)(this.TQ,this),!0,I7(this)?"vtt":void 0,this.g.nh())}};
g.h.unload=function(){if(I7(this))for(var a=g.Xd(window.document,"track",void 0,this.U.app.D.g),b=0;b<a.length;b++)g.qe(a[b]);else g.ut(this.ga),g.dV(this.g,"captions"),this.J=[],this.B&&this.B.Hd(),this.G&&g.aV(this.g,this.G),this.Et();g.sV.prototype.unload.call(this);(a=g.MU(this.g.app))&&a.C&&g.LP(a.C.A);this.g.za("captionschanged",{})};
g.h.TQ=function(){if(this.O||rva(this))var a=sva(this,this.O);if(I7(this))for(var b=v7(this.B.o,!0),c=0;c<b.length;c++){var d=b[c],e={kind:"subtitles",label:g.pI(d),srclang:K6(d),src:this.B.zk(d)};d==a&&(e["default"]=1);for(var d=this.U.app.D,e=[g.he("TRACK",e)],f=0;f<e.length;f++)d.g.appendChild(e[f])}else!this.A&&a&&M7(this,a),this.g.za("onCaptionsTrackListChanged"),this.g.za("onApiChange")};
g.h.YS=function(){this.loaded&&!I7(this)&&this.unload()};
g.h.IA=function(a,b,c,d){if(a){this.B.ZA()&&(this.J=[],g.dV(this.U,"captions"),this.da.Bk());a=pva(this.B,a,b,c,d);c={trackName:b.C,trackKind:b.B,trackLangCode:K6(b)};b.g&&(c.fromLangCode=b.o);g.VU(this.g,"cc",c);if(this.A!=(this.D&&this.D.tk)){if(this.O&&!g.AK(this.Z)&&!g.AN(this.Z)){g.ut(this.ga);b=Q6({Og:0,ki:5,Di:5,mo:2,textAlign:P7.Du,Kj:R6.jp,lang:"en"});this.M=[b];c=g.T("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON");this.fa||(d=new g.WQ(g.kE()),g.L(this,d),this.fa=d.element);d=b.end-b.start;
var e=g.pI(this.A);e&&this.M.push(new N6(b.start,d,0,b.id,e));this.M.push(new N6(b.start,d,0,b.id,c[0]),new N6(b.start,d,0,b.id,this.fa,!0),new N6(b.start,d,0,b.id,c[1],!0));g.aV(this.g,this.M);this.ga.ce()}if(this.O||g.AK(this.Z))O7(this,"module-enabled",!0),this.D&&(this.D.g=this.A);(b=g.MU(this.g.app))&&b.C&&g.LP(b.C.A)}g.aV(this.g,a);this.O=!1}};
g.h.xL=function(a){this.J.push(a);this.da.Bk()};
g.h.yL=function(a){g.nb(this.J,a);this.da.Bk()};
g.h.NR=function(a){if(a instanceof O6){var b=this.K[a.id];b&&b.F!=a&&(b.dispose(),delete this.K[a.id],b=null);b||(b=tva(this,a))&&(this.K[a.id]=b)}else b=a.windowId,this.P[b]||(this.P[b]=[]),this.P[b].push(a)};
g.h.cS=function(){uva(this,this.M);this.M=null};
g.h.fC=function(){this.da.stop();Nua(this.P);this.J.sort(g.pJ);var a=this.J;if(this.G){var b=(0,g.se)(a,function(a){return-1==this.G.indexOf(a)},this);
b.length&&(a=b)}(0,g.G)(a,this.NR,this);g.Jb(this.K,function(a,b){this.P[b]?(a.element.parentNode||g.hV(this.g,a.element,5),a.Ai(this.P[b])):(a.dispose(),delete this.K[b])},this)};
g.h.nB=function(){J7(this,{},!0)};
g.h.zq=function(){var a=N7.tb,a={background:a.background,backgroundOpacity:a.Ue,charEdgeStyle:a.Oh,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.Si,textOpacity:a.zh,windowColor:N7.windowColor,windowOpacity:N7.Rj},b=K7(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.Ht=function(a,b){var c={};g.Ba(c,K7(this,"display-settings"));g.Ba(c,a);J7(this,c,b);this.g.Y("captionssettingschanged")};
g.h.Et=function(){!I7(this)&&this.loaded&&(g.Jb(this.K,function(a,b){a.dispose();delete this.K[b]},this),this.fC())};
g.h.Zr=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.Id(b,-2,4);this.Ht({fontSizeIncrement:c});return c;case "reload":b&&!I7(this)&&M7(this,this.A,!0);break;case "stickyLoading":void 0!=b&&this.Z.Fb&&O7(this,"module-enabled",!!b);break;case "track":if(!this.B)return{};if(b){if(I7(this))break;if(!g.wa(b))break;if(g.Ub(b)){M7(this,null,!0);break}for(var d=v7(this.B.o,!0),e=0;e<d.length;e++){var f=d[e];f.o!=b.languageCode||c&&f.D!=b.languageName||(c=b.translationLanguage?
Jua(f,b.translationLanguage):f)}!c||c==this.A&&this.loaded||M7(this,c,!0)}else return this.loaded&&this.A&&this.A!=(this.D&&this.D.tk)?L6(this.A):{};return"";case "tracklist":return this.B?(0,g.H)(v7(this.B.o,b&&b.includeAsr),function(a){return L6(a)}):[];
case "translationLanguages":return this.B?this.B.C:[];case "displaySettings":c=this.zq();if(g.AK(this.Z)&&b&&g.wa(b))if(b.reset)this.nB();else{f={};for(d in b)switch(d){case "color":case "background":case "windowColor":f[d]=wva(b[d],c[d]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[d]=xva(b[d],c[d]);break;case "charEdgeStyle":f[d]=zva(b[d],c[d]);break;case "fontSizeIncrement":f[d]=Cva(b[d],c[d]);break;case "fontFamilyOption":f.fontFamily=Bva(b[d],c[d])}for(e in f)f[e+
"Override"]=!0;this.Ht(f,!0);c=this.zq()}c.fontFamilyOption=Ava[c.fontFamily];c.charEdgeStyle=yva[c.charEdgeStyle];return c;case "sampleSubtitles":I7(this)||void 0==b||vva(this,!!b);break;case "xmlTrack":b&&this.Z.Fb&&!I7(this)&&M7(this,new g.oI({languageName:b.name}),!1,b.xml)}};
g.h.vL=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.Z.Fb&&a.push("stickyLoading","xmlTrack");return a};
g.h.wL=function(){var a=this.A;return a?{cc:a.F}:{}};
g.h.cC=function(){this.loaded&&this.A?(O7(this,"module-enabled",!1),this.unload()):M7(this,this.A||sva(this,!0),!0)};
g.h.EN=function(){this.o.captionTracks.length&&(this.loaded&&this.unload(),qva(this)&&this.load())};window._exportCheck==g.Da&&g.qa("ytmod.player.captions",L7,void 0);})(_yt_player);
