(function(g){var window=this;var Iva=function(a,b,c,d){var e=b.jc();g.S(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.hc(c,d?d:"mqdefault.jpg");var k=b instanceof g.hP?g.yV(b.lengthSeconds):null,l=!!f,f=l&&"RD"==g.NQ(f).type,m=b instanceof g.hP?b.Da:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.T("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.cn(c),is_live:m,is_list:l,is_mix:f,background:d?"background-image: url("+
d+")":""};b instanceof g.PQ&&(c.playlist_length=b.getLength());a.update(c)},R7=function(a,b){g.xV.call(this,{H:"div",
ea:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.o=a;this.O=!1},S7=function(a){g.CZ.call(this,a,{H:"div",
ea:["ytp-thumbnail-overlay","ytp-channel-overlay"],L:[{H:"div",N:"ytp-thumbnail-overlay-image",T:{style:"{{background}}"}},{H:"div",N:"ytp-thumbnail-overlay-curtain"}]})},T7=function(a){var b={H:"div",
N:"ytp-upnext",T:{"aria-label":"{{watch}}"},L:[{H:"div",N:"ytp-thumbnail-overlay-image",T:{style:"{{background}}"}},{H:"div",N:"ytp-thumbnail-overlay-curtain"},{H:"span",N:"ytp-upnext-top",L:[{H:"span",N:"ytp-upnext-header",L:[g.T("YTP_PLAYLIST_UP_NEXT")]},{H:"span",N:"ytp-upnext-title",L:["{{title}}"]},{H:"span",N:"ytp-upnext-author",L:["{{author}}"]}]},{H:"a",N:"ytp-upnext-autoplay-icon",T:{href:"{{url}}","aria-label":g.T("YTP_AUTOPLAY_NEXT")},L:[{H:"svg",T:{height:"100%",version:"1.1",viewBox:"0 0 98 98",
width:"100%"},L:[{H:"circle",N:"ytp-svg-autoplay-circle",T:{cx:"49",cy:"49",fill:"#000","fill-opacity":"0.8",r:"48"}},{H:"circle",N:"ytp-svg-autoplay-ring",T:{cx:"-49",cy:"49","fill-opacity":"0",r:"46.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{H:"polygon",N:"ytp-svg-autoplay-triangle",T:{fill:"#fff",points:"32,27 72,49 32,71"}}]}]},{H:"span",N:"ytp-upnext-bottom",L:[{H:"span",N:"ytp-upnext-cancel"},{H:"span",N:"ytp-upnext-paused",
L:[g.T("YTP_AUTOPLAY_PAUSED_3")]}]},{H:"span",N:"ytp-upnext-close"}]};g.W.call(this,b);this.B=null;var c=this.wa["ytp-upnext-cancel"],b=this.wa["ytp-upnext-close"];this.B=new g.W({H:"button",ea:["ytp-upnext-cancel-button","ytp-button"],T:{tabindex:0,"aria-label":g.T("YTP_AUTOPLAY_CANCEL")},L:[g.T("YTP_CANCEL")]});g.L(this,this.B);this.B.V("click",this.eA,this);this.B.Ia(c);c=new g.W({H:"button",ea:["ytp-upnext-close-button","ytp-button"],T:{"aria-label":g.T("YTP_AUTOPLAY_CANCEL")}});g.L(this,c);c.V("click",
this.eA,this);c.Ia(b);this.o=a;this.K=this.wa["ytp-svg-autoplay-ring"];this.F=this.D=this.A=this.C=null;this.G=new g.rt(this.Bm,5E3,this);g.L(this,this.G);this.J=0;this.R(this.wa["ytp-upnext-autoplay-icon"],"click",this.NP);this.bA();this.R(a,"autonavvisibility",this.bA);this.R(a,"mdxnowautoplaying",this.cP);this.R(a,"mdxautoplaycanceled",this.dP);this.R(a,"mdxautoplayupnext",this.iC);3==this.o.Xa()&&(a=(a=g.LU(g.GU(this.o)))?a.oH():null)&&this.iC(a)},Jva=function(a,b){a.C=b;
Iva(a,b,g.Y(a.o),"hqdefault.jpg")},U7=function(a,b){a.A||(g.fG("a11y-announce",g.T("YTP_PLAYLIST_UP_NEXT")+" "+a.C.title),a.J=(0,g.sG)(),a.A=new g.rt((0,g.y)(a.Fp,a,b),25),a.Fp(b));
g.Ip(a.element,"ytp-upnext-autoplay-paused")},W7=function(a){V7(a);
a.J=(0,g.sG)();a.Fp();g.R(a.element,"ytp-upnext-autoplay-paused")},V7=function(a){a.A&&(a.A.dispose(),a.A=null)},X7=function(a){R7.call(this,a,"subscribecard-endscreen");
var b=a.ia();this.A=new S7(a);g.L(this,this.A);g.hV(this.o,this.A.element,5);this.B=new g.W({H:"div",N:"ytp-subscribe-card",L:[{H:"img",N:"ytp-author-image",T:{src:b.profilePicture}},{H:"div",N:"ytp-subscribe-card-right",L:[{H:"div",N:"ytp-author-name",L:[b.author]},{H:"div",N:"html5-subscribe-button-container"}]}]});g.L(this,this.B);this.B.Ia(this.element);this.C=new g.q1(g.T("YTP_SUBSCRIBE"),null,g.T("YTP_UNSUBSCRIBE"),null,!0,!1,b.Dl,b.subscribed,"trailer-endscreen",null,null,a);g.L(this,this.C);
this.C.Ia(this.B.wa["html5-subscribe-button-container"]);this.hide()},Y7=function(a){var b=g.Y(a),b=b.A&&!b.F;
g.W.call(this,{H:"a",N:"ytp-videowall-still",T:{href:"{{url}}",target:b?"_blank":"","aria-label":"{{watch}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},L:[{H:"div",N:"ytp-videowall-still-image",T:{style:"{{background}}"}},{H:"span",N:"ytp-videowall-still-info",L:[{H:"span",N:"ytp-videowall-still-info-bg",L:[{H:"span",N:"ytp-videowall-still-info-content",T:g.UE||g.Pe?{style:"will-change: opacity"}:void 0,L:[{H:"span",N:"ytp-videowall-still-info-title",L:["{{title}}"]},
{H:"span",N:"ytp-videowall-still-info-author",L:["{{author_and_views}}"]},{H:"span",N:"ytp-videowall-still-info-live",L:[g.T("YTP_LIVE")]},{H:"span",N:"ytp-videowall-still-info-duration",L:["{{duration}}"]}]}]}]},{H:"span",ea:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],L:[{H:"span",N:"ytp-videowall-still-listlabel-icon"},g.T("YTP_PLAYLIST"),{H:"span",N:"ytp-videowall-still-listlabel-length",L:[" (",{H:"span",L:["{{playlist_length}}"]},")"]}]},{H:"span",ea:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],L:[{H:"span",N:"ytp-videowall-still-listlabel-mix-icon"},g.T("YTP_MIX"),{H:"span",N:"ytp-videowall-still-listlabel-length",L:[" (50+)"]}]}]});this.B=b;this.o=a;this.A=null;this.V("click",this.C);this.V("keypress",this.D);g.Y(a).fa&&(a=a.app.da,g.kb(a.A,this),b=String(a.G++),this.element.setAttribute("data-visual-id",b),g.Ke(this,(0,g.y)(a.F,a,this)))},Z7=function(a){R7.call(this,a,"videowall-endscreen");
this.da=a;this.G=0;this.B=[];this.J=this.D=this.C=null;this.K=this.X=!1;this.F=new g.OF(this);g.L(this,this.F);this.M=new g.rt(g.Aa(g.R,this.element,"ytp-show-tiles"),0);g.L(this,this.M);var b=new g.W({H:"button",ea:["ytp-button","ytp-endscreen-previous"],T:{"aria-label":g.T("YTP_PREVIOUS")},L:[g.VD()]});g.L(this,b);b.Ia(this.element);b.V("click",this.HL,this);this.P=new g.WQ({H:"div",N:"ytp-endscreen-content"});g.L(this,this.P);this.P.Ia(this.element);b=new g.W({H:"button",ea:["ytp-button","ytp-endscreen-next"],
T:{"aria-label":g.T("YTP_NEXT")},L:[g.WD()]});g.L(this,b);b.Ia(this.element);b.V("click",this.GL,this);this.A=new T7(a);g.L(this,this.A);g.hV(this.o,this.A.element,5);this.hide()},$7=function(a){return g.iV(a.o)&&a.Kp()&&!a.J},Kva=function(a){return(0,g.H)(a.cg,function(a){return g.uZ(a)})},Lva=function(a,b,c){return 0==b&&a.C.length&&2<=c/2&&2<=c/2&&g.Y(a.o).experiments.g("video_wall_emphasize_first")?4:2},a8=function(a){var b=a.ds();
b!=a.X&&(a.X=b,a.o.Y("autonavvisibility"))},b8=function(a){g.sV.call(this,a);
g.RD({});this.o=null;this.isAvailable=!0;this.A=new g.OF(this);g.L(this,this.A);this.B=g.Y(a);Mva(a)?this.o=new Z7(this.g):this.B.Sa?this.o=new X7(this.g):this.o=new R7(this.g);g.L(this,this.o);g.hV(this.g,this.o.element,5);this.mB();this.A.R(a,"videodatachange",this.mB,this);this.A.R(a,"crn_endscreen",this.iL,this);this.A.R(a,"crx_endscreen",this.jL,this)},Mva=function(a){a=g.Y(a);
return a.Rc&&!a.Sa};g.p(R7,g.xV);R7.prototype.create=function(){this.O=!0};
R7.prototype.destroy=function(){this.O=!1};
R7.prototype.Kp=function(){return!1};
R7.prototype.ds=function(){return!1};g.p(S7,g.CZ);S7.prototype.Lb=function(a){a?this.A.show():this.A.hide()};g.p(T7,g.W);g.h=T7.prototype;g.h.Bm=function(){this.D&&(this.G.stop(),this.Ca(this.F),this.F=null,this.D.close(),this.D=null)};
g.h.bA=function(){this.Lb(g.HU(this.o))};
g.h.EP=function(){window.focus();this.Bm()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.Fp=function(a){a=a||g.Y(this.o).experiments.o("autoplay_time")||1E4;var b=Math.min((0,g.sG)()-this.J,a);a=Math.min(b/a,1);this.K.setAttribute("stroke-dashoffset",-293*(a+1));1<=a&&3!=this.o.Xa()?this.select(!0):this.A&&this.A.start()};
g.h.select=function(a){a=void 0===a?!1:a;var b=g.Y(this.o);if(b.experiments.g("autonav_notifications")&&a&&window.Notification&&window.document.hasFocus){var c=window.Notification.permission;g.VU(this.o,"xwebnotifications",{permission:c});"default"==c?window.Notification.requestPermission():"granted"!=c||window.document.hasFocus()||(c=this.C.jc(),this.Bm(),this.D=new window.Notification(g.T("YTP_PLAYLIST_UP_NEXT"),{body:c.title,icon:c.hc(b)}),this.F=this.R(this.D,"click",this.EP),this.G.start())}V7(this);
this.o.qj(!1,a)};
g.h.NP=function(a){!g.xe(this.B.element,g.EF(a))&&g.eZ(a,this.o)&&this.select()};
g.h.eA=function(){g.WU(this.o,"autonavcancel");g.JU(this.o,!0)};
g.h.cP=function(a){this.o.Xa();this.show();U7(this,a)};
g.h.iC=function(a){this.o.Xa();this.C&&this.C.jc().videoId==a.jc().videoId||Jva(this,a)};
g.h.dP=function(){this.o.Xa();V7(this);this.hide()};
g.h.W=function(){V7(this);this.Bm();g.W.prototype.W.call(this)};g.p(X7,R7);X7.prototype.show=function(){R7.prototype.show.call(this);this.A.Lb(!0)};
X7.prototype.hide=function(){R7.prototype.hide.call(this);this.A.Lb(!1)};g.p(Y7,g.W);Y7.prototype.Ej=function(){var a=this.A.jc().videoId,b=this.A.getPlaylistId();g.r2(this.o.app,a,this.A.Sd,b,void 0,void 0)};
Y7.prototype.C=function(a){g.lV(this.o,this);g.eZ(a,this.o,this.B,this.A.Sd||void 0)&&this.Ej()};
Y7.prototype.D=function(a){switch(a.keyCode){case 13:case 32:g.JF(a)||(this.Ej(),g.LF(a))}};g.p(Z7,R7);g.h=Z7.prototype;g.h.create=function(){R7.prototype.create.call(this);var a=this.o.ia();a&&(this.C=Kva(a),this.D=a);this.qh();this.F.R(this.o,"appresize",this.qh);this.F.R(this.o,"videodatachange",this.IL);this.F.R(this.o,"autonavchange",this.dz);this.F.R(this.o,"autonavcancel",this.FL);this.F.R(this.element,"transitionend",this.UQ)};
g.h.destroy=function(){g.QF(this.F);g.Me(this.B);this.B=[];this.C=null;R7.prototype.destroy.call(this);g.Ip(this.element,"ytp-show-tiles");this.M.stop()};
g.h.Kp=function(){return 1!=this.D.autonavState};
g.h.show=function(){R7.prototype.show.call(this);g.Ip(this.element,"ytp-show-tiles");g.Y(this.o).isMobile?g.tt(this.M):this.M.start();(this.K||this.J&&this.J!=this.D.clientPlaybackNonce)&&g.JU(this.o,!1);var a=$7(this);g.iV(this.o)&&g.Y(this.o).experiments.g("ui_logging")&&g.VU(this.o,"end",{cancelButtonShow:a?"1":"0",state:this.Kp()?"enabled":"disabled"});a?(a8(this),2==this.D.autonavState?g.Y(this.o).experiments.g("fast_autonav_in_background")&&3==this.o.In()?this.A.select(!0):U7(this.A):3==this.D.autonavState&&
W7(this.A)):(g.JU(this.o,!0),a8(this))};
g.h.hide=function(){R7.prototype.hide.call(this);W7(this.A);a8(this)};
g.h.UQ=function(a){g.EF(a)==this.element&&this.qh()};
g.h.qh=function(){if(this.C&&this.C.length){g.R(this.element,"ytp-endscreen-paginate");var a=g.th(this.element),b=a.width/a.height,c=96/54,d=2,e=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2),n=Lva(this,0,k),q=Lva(this,1,k);var r=l*m+(Math.pow(n,2)-m);r+=Math.pow(q,2)-m;for(r-=m;0<r&&(d<f||e<k);){var w=d/2,A=e/2,C=d<=f-2&&r>=A*m,B=e<=k-2&&r>=w*m;if((w+1)/A*c/b>b/(w/(A+1)*c)&&B)r-=w*m,e+=2;else if(C)r-=A*m,d+=2;else if(B)r-=w*m,e+=2;else break}c=!1;f=2+n;r>=3*
m&&6>=l*m-r&&(e>=f||d>=f)&&2>=q&&(c=!0);m=96*d;r=54*e;b=m/r<b?a.height/r:a.width/m;b=Math.min(b,2);m*=b;r*=b;m*=g.Id(a.width/m||1,1,1.21);r*=g.Id(a.height/r||1,1,1.21);m=Math.floor(Math.min(a.width,m));r=Math.floor(Math.min(a.height,r));a=this.P.element;g.sh(a,m,r);g.ah(a,{marginLeft:m/-2+"px",marginTop:r/-2+"px"});Jva(this.A,this.C[0]);g.S(this.element,"ytp-endscreen-takeover",$7(this));a8(this);m+=4;r+=4;b=0;f=!1;for(k=0;k<d;k++)for(w=0;w<e;w++)if(A=2<q&&1<=b&&!f?b+1:b,C=0,c&&k>=d-2&&w>=e-2?C=1:
0==w%2&&0==k%2&&(w<n&&k<n?0==w&&0==k&&(C=n):2<q&&w>=e-q&&k>=d-q?w==e-q&&k==d-q&&(f=!0,A=1,C=q):C=2),A=g.Kd(A+this.G,l),0!=C){B=this.B[b];B||(B=new Y7(this.o),this.B[b]=B,a.appendChild(B.element));var M=Math.floor(r*w/e),X=Math.floor(m*k/d),xa=Math.floor(r*(w+C)/e)-M-4,db=Math.floor(m*(k+C)/d)-X-4;g.hh(B.element,X,M);g.sh(B.element,db,xa);g.ah(B.element,"transitionDelay",(w+k)/20+"s");g.S(B.element,"ytp-videowall-still-mini",1==C);g.S(B.element,"ytp-videowall-still-large",2<C);C=B;A=this.C[A];C.A=
A;Iva(C,A,g.Y(C.o),g.Gp(C.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");B=A.Sd;A=C.o;g.Y(A).fa&&(A=A.app.da,B=B&&B.itct,C=C.element.getAttribute("data-visual-id"),g.jV(A,"onLogServerVeCreated",{id:C,tracking_params:B}));b++}g.S(this.element,"ytp-endscreen-paginate",b<l);for(d=this.B.length-1;d>=b;d--)e=this.B[d],g.qe(e.element),g.Le(e);this.B.length=b}};
g.h.IL=function(){var a=this.o.ia();this.D!=a&&(this.G=0,this.C=Kva(a),this.D=a,this.qh())};
g.h.GL=function(){this.G+=this.B.length;this.qh()};
g.h.HL=function(){this.G-=this.B.length;this.qh()};
g.h.xJ=function(){return!!this.A.A};
g.h.dz=function(a){1==a?(this.K=!1,this.J=this.D.clientPlaybackNonce,V7(this.A),this.g&&this.qh()):(this.K=!0,this.g&&$7(this)&&(2==a?U7(this.A):3==a&&W7(this.A)))};
g.h.FL=function(a){if(a){for(a=0;a<this.B.length;a++)g.mV(this.da,this.B[a],!0);this.dz(1)}else this.J=null,this.K=!1;this.qh()};
g.h.ds=function(){return this.g&&$7(this)};g.p(b8,g.sV);g.h=b8.prototype;g.h.Zy=function(){var a=this.g.ia(),b=!Mva(this.g)||!(!a.cg||!a.cg.length),a=g.CP(a,"ypc_module"),c=g.EZ(this.g.app);return(b||!1)&&!a&&!c};
g.h.Yy=function(){return this.o.ds()};
g.h.uJ=function(){return this.Yy()?this.o.xJ():!1};
g.h.W=function(){g.dV(this.g,"endscreen");g.sV.prototype.W.call(this)};
g.h.load=function(){g.sV.prototype.load.call(this);this.o.show();g.Y(this.g).Sa&&.01>Math.random()&&g.VU(this.g,"end",{trailerEndscreenShow:1})};
g.h.unload=function(){g.sV.prototype.unload.call(this);this.o.hide();this.o.destroy();this.isAvailable=!1};
g.h.iL=function(a){this.Zy()&&(this.o.O||this.o.create(),"load"==a.getId()&&this.load())};
g.h.jL=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.mB=function(){g.dV(this.g,"endscreen");var a=Math.max(1E3*(this.g.ia().lengthSeconds-10),0),a=new g.oJ(a,0x8000000000000,{id:"preload",namespace:"endscreen"}),b=new g.oJ(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.aV(this.g,[a,b])};window._exportCheck==g.Da&&g.qa("ytmod.player.endscreen",b8,void 0);})(_yt_player);
